export default () => [
  `at the end of the day...`,
  `as we speak`,
  `give you a heads-up`,
  `take that offline`,
  `synergy`,
  `customer-centric`,
  `lines were crossed`,
  `sweet spot`,
  `multitasking`,
  `one-off`,
  `next-generation`,
  `mission-critical`,
  `push back`,
  `takeaway`,
  `outsource`,
  `downsize`,
  `ballpark figure`,
  `enable`,
  `herding cats`,
  `leverage`,
  `make it pop`,
  `unicorn`,
  `outside the box`,
  `going forward`,
  `let's circle back`,
]
